export const SIGNUP_LOADING="SIGNUP_LOADING"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_ERROR="SIGNUP_ERROR"

export const GOOGLE_SIGNUP_LOADING="GOOGLE_SIGNUP_LOADING"
export const GOOGLE_SIGNUP_SUCCESS="GOOGLE_SIGNUP_SUCCESS"
export const GOOGLE_SIGNUP_ERROR="GOOGLE_SIGNUP_ERROR"


export const LOGIN_LOADING="LOGIN_LOADING"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_ERROR="LOGIN_ERROR"


export const LOGOUT_LOADING="LOGOUT_LOADING"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_ERROR="LOGOUT_ERROR";

export const SET_USER="SET_USER";
