//for all products
export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCESS="GET_PRODUCTS_SUCESS"
export const GET_PRODUCTS_ERROR="GET_PRODUCTS_ERROR";

//for single products page
export const GET_SINGLE_PRODUCTS_REQUEST="GET_SINGLE_PRODUCTS_REQUEST";
export const GET_SINGLE_PRODUCTS_SUCESS="GET_SINGLE_PRODUCTS_SUCESS"
export const GET_SINGLE_PRODUCTS_ERROR="GET_SINGLE_PRODUCTS_ERROR";
//for add to cart
export const ADD_CART_REQ="ADD_CART_REQ";
export const ADD_CART_SUCESS="ADD_CART_SUCESS";
export const ADD_CART_ERROR="ADD_CART_ERROR";

//for get data from cart
export const GET_CART_REQ="GET_CART_REQ";
export const GET_CART_SUCESS="GET_CART_SUCESS";
export const GET_CART_ERROR="GET_CART_ERROR";

//for cart page for quantity
export const UPDATE_CART_REQUEST = 'cart/UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCESS = 'cart/UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'cart/UPDATE_CART_FAILURE';

//delete from cart
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";




