export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCESS="GET_PRODUCTS_SUCESS"
export const GET_PRODUCTS_ERROR="GET_PRODUCTS_ERROR";

export const ADD_CART_REQ="ADD_CART_REQ";
export const ADD_CART_SUCESS="ADD_CART_SUCESS";
export const ADD_CART_ERROR="ADD_CART_ERROR";

export const GET_CART_REQ="GET_CART_REQ";
export const GET_CART_SUCESS="GET_CART_SUCESS";
export const GET_CART_ERROR="GET_CART_ERROR";





